// vue/src/components/atoms/Toast/index.vue
<script lang="ts" setup>
import { computed, ref, watch } from "vue";

type Props = {
  isShown: boolean;
};

/* to give enough time for inspection when presenting */
const PROPS_SHOW_DURATION = 10_000;

const props = defineProps<Props>();
const emit = defineEmits(["clear"]);

/* progress */
const timeProgress = ref<number>(0);
const progressWidth = computed(
  () => `${100 - (timeProgress.value / PROPS_SHOW_DURATION) * 100}%`,
);
const raf = ref<number>();
const rafStartTime = ref<number>();
const rafCallback = (timestamp: number) => {
  if (!rafStartTime.value) {
    rafStartTime.value = timestamp;
  }

  timeProgress.value = timestamp - rafStartTime.value;
  if (timeProgress.value >= PROPS_SHOW_DURATION) {
    emit("clear");
    return;
  }

  raf.value = window.requestAnimationFrame(rafCallback);
};

watch(
  () => props.isShown,
  (isShown) => {
    if (raf.value) window.cancelAnimationFrame(raf.value);
    raf.value = undefined;
    if (!isShown) return;

    raf.value = window.requestAnimationFrame(rafCallback);
  },
);

/* ref expose demonstration */
defineExpose({
  clear: () => {
    if (!props.isShown) return;
    emit("clear");
  },
});
</script>
<template>
  <Teleport to="body">
    <div v-if="isShown" :class="[$style.toast, $style.toast__vue]">
      <slot></slot>
      <div :class="[$style.toast_progress]" :style="{ width: progressWidth }" />
    </div>
  </Teleport>
</template>
<style module>
@import url("common/css/toast.module.css");
</style>

// react/src/components/atoms/Toast/index.tsx
import {
  forwardRef,
  useCallback,
  useEffect,
  useImperativeHandle,
  useRef,
  useState,
} from "react";
import styles from "common/css/toast.module.css";
import { createPortal } from "react-dom";

type Props = {
  isShown: boolean;
  onClear: () => void;
  children: React.ReactNode;
};

/* to give enough time for inspection when presenting */
const PROPS_SHOW_DURATION = 10_000;

export const Toast = forwardRef<{ clear: Props["onClear"] }, Props>(
  ({ isShown, onClear, children }, ref) => {
    /* progress */
    const [timeProgress, setTimeProgres] = useState(0);
    const progressWidth = `${100 - (timeProgress / PROPS_SHOW_DURATION) * 100}%`;

    const raf = useRef<number>();
    const rafStartTime = useRef<number>();
    const rafCallback = useCallback(
      (timestamp: number) => {
        if (!rafStartTime.current) {
          rafStartTime.current = timestamp;
        }

        const currentTimeProgress = timestamp - rafStartTime.current;
        if (currentTimeProgress >= PROPS_SHOW_DURATION) {
          onClear();
          return;
        }

        raf.current = window.requestAnimationFrame(rafCallback);
        setTimeProgres(currentTimeProgress);
      },
      [onClear],
    );

    useEffect(() => {
      if (raf.current) window.cancelAnimationFrame(raf.current);
      raf.current = undefined;
      if (!isShown) return;

      rafStartTime.current = undefined;
      raf.current = window.requestAnimationFrame(rafCallback);
    }, [rafCallback, isShown]);

    /* ref expose demonstration */
    useImperativeHandle(ref, () => ({ clear: onClear }));

    return createPortal(
      <div
        className={`${styles.toast} ${styles.toast__react}`}
        style={{ display: isShown ? "block" : "none" }}
      >
        {children}
        <div
          className={styles.toast_progress}
          style={{ width: progressWidth }}
        />
      </div>,
      document.body,
    );
  },
);
