// vue/src/App.vue
<script setup lang="ts">
import { computed } from "vue";
import { useRoute } from "vue-router";

type Link = {
  to: string;
  text: string;
};

const links: Link[] = [
  { to: "/", text: "Home" },
  { to: "/counter", text: "Counter" },
];

const route = useRoute();
const activeLink = computed(() => links.find((link) => link.to === route.path));
</script>

<template>
  <div :class="$style.app">
    <header :class="[$style.app_header, $style.header]">
      <div :class="[$style.header_label, $style.header_label__vue]">Vue</div>
      <div :class="$style.header_text">シンプルなvue3とReact比較</div>
    </header>
    <aside :class="$style.app_aside">
      <div :class="$style.link_activeRoute">
        <div>Active route:</div>
        <div>{{ activeLink?.to }}</div>
      </div>
      <nav :class="$style.link_list">
        <template v-for="{ to, text } in links" :key="to">
          <router-link
            :to="to"
            :class="[
              $style.link_item,
              to === activeLink?.to ? $style.link_item__active : '',
            ]"
          >
            {{ text }}
          </router-link>
        </template>
      </nav>
    </aside>
    <main :class="$style.app_main"><router-view /></main>
  </div>
</template>

<style module>
@import url("common/css/app.module.css");
</style>

// react/src/App.tsx
import { Outlet, Link, useMatches } from "react-router-dom";
import styles from "common/css/app.module.css";

type Link = {
  to: string;
  text: string;
};

const links: Link[] = [
  { to: "/", text: "Home" },
  { to: "/counter", text: "Counter" },
];

export const App: React.FC = () => {
  const matches = useMatches();
  const activeLink = [...links]
    .reverse()
    .find((link) => matches.some((match) => match.pathname === link.to));

  return (
    <div className={styles.app}>
      <header className={[styles.app_header, styles.header].join(" ")}>
        <div
          className={[styles.header_label, styles.header_label__react].join(
            " ",
          )}
        >
          React
        </div>
        <div className={styles.header_text}>シンプルなvue3とReact比較</div>
      </header>
      <aside className={styles.app_aside}>
        <div className={styles.link_activeRoute}>
          <div>Active route:</div>
          <div>{activeLink?.to}</div>
        </div>
        <nav className={styles.link_list}>
          {links.map(({ to, text }) => (
            <Link
              key={to}
              to={to}
              className={[
                styles.link_item,
                to === activeLink?.to ? styles.link_item__active : "",
              ].join(" ")}
            >
              {text}
            </Link>
          ))}
        </nav>
      </aside>
      <main className={styles.app_main}>
        <Outlet />
      </main>
    </div>
  );
};
