// vue/src/components/pages/Todo/index.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import TextInput from "@/components/atoms/TextInput/index.vue";
import Toast from "@/components/atoms/Toast/index.vue";
import { useToast } from "@/components/atoms/Toast/useToast";
import CheckboxWithLabel from "@/components/atoms/CheckboxWithLabel/index.vue";
import type {
  Task,
  TabStatus,
  Tab,
} from "../../../../../common/script/types/todo";

/* Tabs */
const tabs: Tab[] = [
  { status: "all", text: "All" },
  { status: "in-progress", text: "In Progress" },
  { status: "done", text: "Done" },
];
const currentTab = ref<TabStatus>("all");

/* Toast */
const { toastText, clearToast, showToast } = useToast();
const toastRef = ref<InstanceType<typeof Toast>>();
const clearToastManually = () => {
  toastRef.value?.clear();
};

/* Task List */
const tasks = ref<Task[]>([]);
const shownTasks = computed(() =>
  tasks.value.filter((task) => {
    if (currentTab.value === "all") {
      return true;
    }
    return task.status === currentTab.value;
  }),
);

/* Create New Task */
const newTaskName = ref<string>("");
const createNewTask = () => {
  tasks.value.push({
    id: Date.now().toString(),
    name: newTaskName.value,
    status: "in-progress",
  });

  showToast(`Task "${newTaskName.value}" created!`);
  newTaskName.value = "";
};

/* Check Task */
const handleCheck = (id: string, isChecked: boolean) => {
  const task = tasks.value.find((task) => task.id === id);
  if (!task) return;

  task.status = isChecked ? "done" : "in-progress";
  showToast(`Task "${task.name}" ${isChecked ? "completed!" : "in progress!"}`);
};
</script>
<template>
  <h1>Todo App</h1>
  <nav :class="$style.nav">
    <template v-for="tab in tabs" :key="tab.status">
      <div
        :class="{
          [$style.nav_item]: true,
          [$style.nav_item__active]: tab.status === currentTab,
        }"
        @click="currentTab = tab.status"
      >
        {{ tab.text }}
      </div>
    </template>
  </nav>
  <section :class="$style.task_list">
    <template v-if="shownTasks.length > 0">
      <template v-for="task in shownTasks" :key="task.id">
        <CheckboxWithLabel
          :class="$style.task_item"
          :data-checked="task.status === 'done'"
          :is-checked="task.status === 'done'"
          :label="task.name"
          @check="handleCheck(task.id, $event)"
        />
      </template>
    </template>
    <template v-else>
      <span>No tasks</span>
    </template>
  </section>
  <div>
    <TextInput v-model="newTaskName" />
    <button
      :disabled="!newTaskName"
      :class="$style.todo_submitBtn"
      @click="createNewTask"
    >
      Submit
    </button>
  </div>
  <template v-if="toastText">
    <button @click="clearToastManually">Clear Toast Manually</button>
  </template>
  <Toast ref="toastRef" @clear="clearToast">{{ toastText }}</Toast>
</template>
<style module>
@import url("common/css/todo.module.css");
</style>

// react/src/components/pages/Todo/index.tsx
import { useMemo, useRef, useState } from "react";
import { TextInput } from "@/components/atoms/TextInput";
import { Toast } from "@/components/atoms/Toast";
import { useToast } from "@/components/atoms/Toast/useToast";
import { CheckboxWithLabel } from "@/components/atoms/CheckboxWithLabel";
import styles from "common/css/todo.module.css";
import type {
  Task,
  TabStatus,
  Tab,
} from "../../../../../common/script/types/todo";

const tabs: Tab[] = [
  { status: "all", text: "All" },
  { status: "in-progress", text: "In Progress" },
  { status: "done", text: "Done" },
];

export const Todo: React.FC = () => {
  /* Tabs */
  const [currentTab, setCurrentTab] = useState<TabStatus>("all");

  /* Toast */
  const { toastText, clearToast, showToast } = useToast();
  const toastRef = useRef<React.ElementRef<typeof Toast>>(null);
  const clearToastManually = () => {
    toastRef.current?.clear();
  };

  /* Task List */
  const [tasks, setTasks] = useState<Task[]>([]);
  const shownTasks = useMemo(
    () =>
      tasks.filter((task) => {
        if (currentTab === "all") {
          return true;
        }
        return task.status === currentTab;
      }),
    [currentTab, tasks],
  );

  /* Create New Task */
  const [newTaskName, setNewTaskName] = useState<string>("");
  const handleNewTaskNameChange = (value: string) => {
    setNewTaskName(value);
  };
  const createNewTask = () => {
    setTasks((currentTasks) => [
      ...currentTasks,
      {
        id: Date.now().toString(),
        name: newTaskName,
        status: "in-progress",
      },
    ]);

    showToast(`Task "${newTaskName}" created!`);
    setNewTaskName("");
  };

  /* Check Task */
  const handleCheck = (id: string, isChecked: boolean) => {
    const task = tasks.find((task) => task.id === id);
    if (!task) return;

    task.status = isChecked ? "done" : "in-progress";
    showToast(
      `Task "${task.name}" ${isChecked ? "completed!" : "in progress!"}`,
    );
  };

  return (
    <>
      <h1>Todo App</h1>
      <nav className={styles.nav}>
        {tabs.map((tab) => (
          <div
            key={tab.status}
            className={`${styles.nav_item} ${
              tab.status === currentTab ? styles.nav_item__active : ""
            }`}
            onClick={() => {
              setCurrentTab(tab.status);
            }}
          >
            {tab.text}
          </div>
        ))}
      </nav>
      <section className={styles.task_list}>
        {shownTasks.length > 0 ? (
          shownTasks.map((task) => (
            <div
              key={task.id}
              className={styles.task_item}
              data-checked={task.status === "done"}
            >
              <CheckboxWithLabel
                aria-label={task.name}
                isChecked={task.status === "done"}
                label={task.name}
                onCheckboxChange={(isChecked: boolean) => {
                  handleCheck(task.id, isChecked);
                }}
              />
            </div>
          ))
        ) : (
          <span>No tasks</span>
        )}
      </section>
      <div>
        <TextInput value={newTaskName} onChange={handleNewTaskNameChange} />
        <button
          className={styles.todo_submitBtn}
          disabled={!newTaskName}
          onClick={createNewTask}
        >
          Submit
        </button>
      </div>
      {toastText && (
        <button onClick={clearToastManually}>Clear Toast Manually</button>
      )}
      <Toast onClear={clearToast} ref={toastRef}>
        {toastText}
      </Toast>
    </>
  );
};
