// vue/src/components/pages/Counter/index.vue
<script setup lang="ts">
import { computed, ref } from "vue";

const count = ref(0);
const canDecrease = computed(() => count.value > 0);

const increase = () => {
  count.value += 1;
};
const decrease = () => {
  if (count.value <= 0) return;
  count.value -= 1;
};
</script>

<template>
  <div>
    <div :class="$style.count">currentCount: {{ count }}</div>
    <button :class="$style.button" :disabled="!canDecrease" @click="decrease">
      -
    </button>
    <button :class="$style.button" @click="increase">+</button>
  </div>
</template>

<style module>
.count {
  margin-block-end: 10px;
}

.button {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 20px;
  height: 20px;
}
</style>

// react/src/components/Counter/index.tsx
import styles from "./index.module.css";
import { useState } from "react";

export const Counter: React.FC = () => {
  const [count, setCount] = useState(0);
  const canDecrease = count > 0;

  const increase = () => setCount(count + 1);
  const decrease = () => {
    if (count <= 0) return;
    setCount(count - 1);
  };

  return (
    <div>
      <div className={styles.count}>currentCount: {count}</div>
      <button onClick={decrease} disabled={!canDecrease}>
        -
      </button>
      <button onClick={increase}>+</button>
    </div>
  );
};
