// vue/src/components/pages/Theme/index.vue
<script setup lang="ts">
import { useInjectTheme } from "@/composables/contexts/useProvideTheme";
import { onMounted, onUnmounted } from "vue";

const { setDefaultTheme, toggleTheme } = useInjectTheme();

onMounted(setDefaultTheme);
onUnmounted(setDefaultTheme);
</script>
<template>
  <div>
    <button @click="toggleTheme">toggle theme</button>
  </div>
</template>

// react/src/components/pages/Theme/index.tsx
import { useContext, useEffect } from "react";
import { ThemeContext } from "@/composables/contexts/useThemeContext";

export const Theme: React.FC = () => {
  const { setDefaultTheme, toggleTheme } = useContext(ThemeContext);

  useEffect(() => {
    setDefaultTheme();
    return setDefaultTheme;
  }, [setDefaultTheme]);
  return (
    <div>
      <button onClick={toggleTheme}>toggle theme</button>
    </div>
  );
};
