// react/src/components/atoms/CheckboxWithLabel/index.tsx
import styles from "./index.module.css";

type Props = {
  className?: string;
  label: string;
  isChecked: boolean;
  onCheckboxChange: (isChecked: boolean) => void;
};

export const CheckboxWithLabel: React.FC<Props> = ({
  className = "",
  label,
  isChecked = false,
  onCheckboxChange,
}) => {
  const handleChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    onCheckboxChange(event.target.checked);
  };

  return (
    <label className={`${styles.checkboxWithLabel} ${className}`}>
      <input
        type="checkbox"
        className={styles.CheckboxWithLabel_checkbox}
        defaultChecked={isChecked}
        onChange={handleChange}
      />
      {label}
    </label>
  );
};

// vue/src/components/atoms/CheckboxWithLabel/index.vue
<script setup lang="ts">
withDefaults(defineProps<{ label: string; isChecked: boolean }>(), {
  isChecked: false,
});

const emit = defineEmits(["check"]);

const handleCheck = (e: Event) => {
  if (!e.target) return;
  emit("check", (e.target as HTMLInputElement).checked);
};
</script>
<template>
  <label :class="$style.checkboxWithLabel">
    <input
      :checked="isChecked"
      :class="$style.checkboxWithLabel_checkbox"
      type="checkbox"
      @change="handleCheck"
    />
    <span>{{ label }}</span>
  </label>
</template>
<style module>
.checkboxWithLabel {
  display: flex;
  align-items: center;
}

.checkboxWithLabel_checkbox {
  margin-inline-start: 8px;
}
</style>
